class ManipulacaoForm():
    def preencher(form, video):
        form.g_i_catalogo.data = video['geral']['identificador']['catalogo']
        form.g_i_entrada.data = video['geral']['identificador']['entrada']
        form.g_titulo.data = video['geral']['titulo']
        form.g_idioma.data = video['geral']['idioma']
        form.g_descricao.data = video['geral']['descricao']
        form.g_palavras_chave.data = video['geral']['palavras_chave']
        form.g_cobertura.data = video['geral']['cobertura']
        form.g_estrutura.data = video['geral']['estrutura']
        form.g_nivel_de_agregacao.data = video['geral']['nivel_de_agregacao']
        form.g_subnivel_de_agregacao.data = video['geral']['subnivel_de_agregacao']
        form.g_outros_termos.data = video['geral']['outros_termos']
        form.g_termos.data = video['geral']['termos']

        # form.versao.data = video['ciclo_de_vida']['versao']
        # form.status.data = video['ciclo_de_vida']['status']
        # form.entidade.data = video['ciclo_de_vida']['contribuinte']['entidade']
        # form.data.data = video['ciclo_de_vida']['contribuinte']['data']
        # form.papel.data = video['ciclo_de_vida']['contribuinte']['papel']
        # form.i_catalogo.data = video['meta_metadados']['identificador']['catalogo']
        # form.i_entrada.data = video['meta_metadados']['identificador']['entrada']
        # form.c_entidade.data = video['meta_metadados']['contribuinte']['entidade']
        # form.c_data.data = video['meta_metadados']['contribuinte']['data']
        # form.c_papel.data = video['meta_metadados']['contribuinte']['papel']
        # form.esquema_de_metadados.data = video['meta_metadados']['esquema_de_metadados']
        # form.m_idioma.data = video['meta_metadados']['idioma']
        # form.m_formato.data = video['dados_tecnicos']['formato']
        # form.m_tamanho.data = video['dados_tecnicos']['tamanho']
        # form.m_localizacao.data = video['dados_tecnicos']['localizacao']
        # form.m_requisitos.data = video['dados_tecnicos']['requisitos']
        # form.m_observacoes_de_Instalacoes.data = video['dados_tecnicos']['observacoes_de_Instalacoes']
        # form.m_outros_requisitos_de_sistema.data = video['dados_tecnicos']['outros_requisitos_de_sistema']
        # form.m_duracao.data = video['dados_tecnicos']['duracao']
        # form.ae_tipo_de_interatividade.data = video['aspectos_educacionais']['tipo_de_interatividade']
        # form.ae_tipo_de_recurso_de_aprendizado.data = video['aspectos_educacionais']['tipo_de_recurso_de_aprendizado']
        # form.ae_nivel_de_interatividade.data = video['aspectos_educacionais']['nivel_de_interatividade']
        # form.ae_densidade_semantica.data = video['aspectos_educacionais']['densidade_semantica']
        # form.ae_usuario_final.data = video['aspectos_educacionais']['usuario_final']
        # form.ae_contexto_de_aprendizagem.data = video['aspectos_educacionais']['contexto_de_aprendizagem']
        # form.ae_idade_recomendada.data = video['aspectos_educacionais']['idade_recomendada']
        # form.ae_grau_de_dificuldade.data = video['aspectos_educacionais']['grau_de_dificuldade']
        # form.ae_tempo_de_aprendizado.data = video['aspectos_educacionais']['tempo_de_aprendizado']
        # form.ae_descricao.data = video['aspectos_educacionais']['descricao']
        # form.ae_linguagem.data = video['aspectos_educacionais']['linguagem']
        # form.d_custo.data = video['direitos']['custo']
        # form.d_direitos_autorais.data = video['direitos']['direitos_autorais']
        # form.d_descricao.data = video['direitos']['descricao']
        # form.r_genero.data = video['relacoes']['genero']
        # form.r_recurso_referencias.data = video['relacoes']['recurso']['referencias']
        # form.r_recurso_links_externos.data = video['relacoes']['recurso']['links_externos']
        # form.c_finalidade.data = video['classificacao']['finalidade']
        # form.c_diretorio.data = video['classificacao']['diretorio']
        # form.c_descricao.data = video['classificacao']['descricao']
        # form.c_palavra_chave.data = video['classificacao']['palavra_chave']
        # form.cont_data.data = video['conteudo']['data']
        # form.cont_entidade.data = video['conteudo']['entidade']
        # form.cont_imagens.data = video['conteudo']['imagens']
        # form.cont_comentarios.data = video['conteudo']['comentarios']
        return form

    def atualizarObjeto(form, video):
        video['geral']['identificador']['catalogo'] = form.g_i_catalogo.data
        video['geral']['identificador']['entrada'] = form.g_i_entrada.data
        video['geral']['titulo'] = form.g_titulo.data
        video['geral']['idioma'] = form.g_idioma.data
        video['geral']['descricao'] = form.g_descricao.data
        video['geral']['palavras_chave'] = form.g_palavras_chave.data
        video['geral']['cobertura'] = form.g_cobertura.data
        video['geral']['estrutura'] = form.g_estrutura.data
        video['geral']['nivel_de_agregacao'] = form.g_nivel_de_agregacao.data
        video['geral']['subnivel_de_agregacao'] = form.g_subnivel_de_agregacao.data
        video['geral']['outros_termos'] = form.g_outros_termos.data
        video['geral']['termos'] = form.g_termos.data

        # video['ciclo_de_vida']['versao'] = form.versao.data
        # video['ciclo_de_vida']['status'] = form.status.data
        # video['ciclo_de_vida']['contribuinte']['entidade'] = form.entidade.data
        # video['ciclo_de_vida']['contribuinte']['data'] = form.data.data
        # video['ciclo_de_vida']['contribuinte']['papel'] = form.papel.data
        # video['meta_metadados']['identificador']['catalogo'] = form.i_catalogo.data
        # video['meta_metadados']['identificador']['entrada'] = form.i_entrada.data
        # video['meta_metadados']['contribuinte']['entidade'] = form.c_entidade.data
        # video['meta_metadados']['contribuinte']['data'] = form.c_data.data
        # video['meta_metadados']['contribuinte']['papel'] = form.c_papel.data
        # video['meta_metadados']['esquema_de_metadados'] = form.esquema_de_metadados.data
        # video['meta_metadados']['idioma'] = form.m_idioma.data
        # video['dados_tecnicos']['formato'] = form.m_formato.data
        # video['dados_tecnicos']['tamanho'] = form.m_tamanho.data
        # video['dados_tecnicos']['localizacao'] = form.m_localizacao.data
        # video['dados_tecnicos']['requisitos'] = form.m_requisitos.data
        # video['dados_tecnicos']['observacoes_de_Instalacoes'] = form.m_observacoes_de_Instalacoes.data
        # video['dados_tecnicos']['outros_requisitos_de_sistema'] = form.m_outros_requisitos_de_sistema.data
        # video['dados_tecnicos']['duracao'] = form.m_duracao.data
        # video['aspectos_educacionais']['tipo_de_interatividade'] = form.ae_tipo_de_interatividade.data
        # video['aspectos_educacionais']['tipo_de_recurso_de_aprendizado'] = form.ae_tipo_de_recurso_de_aprendizado.data
        # video['aspectos_educacionais']['nivel_de_interatividade'] = form.ae_nivel_de_interatividade.data
        # video['aspectos_educacionais']['densidade_semantica'] = form.ae_densidade_semantica.data
        # video['aspectos_educacionais']['usuario_final'] = form.ae_usuario_final.data
        # video['aspectos_educacionais']['contexto_de_aprendizagem'] = form.ae_contexto_de_aprendizagem.data
        # video['aspectos_educacionais']['idade_recomendada'] = form.ae_idade_recomendada.data
        # video['aspectos_educacionais']['grau_de_dificuldade'] = form.ae_grau_de_dificuldade.data
        # video['aspectos_educacionais']['tempo_de_aprendizado'] = form.ae_tempo_de_aprendizado.data
        # video['aspectos_educacionais']['descricao'] = form.ae_descricao.data
        # video['aspectos_educacionais']['linguagem'] = form.ae_linguagem.data
        # video['direitos']['custo'] = form.d_custo.data
        # video['direitos']['direitos_autorais'] = form.d_direitos_autorais.data
        # video['direitos']['descricao'] = form.d_descricao.data
        # video['relacoes']['genero'] = form.r_genero.data
        # video['relacoes']['recurso']['referencias'] = form.r_recurso_referencias.data
        # video['relacoes']['recurso']['links_externos'] = form.r_recurso_links_externos.data
        # video['classificacao']['finalidade'] = form.c_finalidade.data
        # video['classificacao']['diretorio'] = form.c_diretorio.data
        # video['classificacao']['descricao'] = form.c_descricao.data
        # video['classificacao']['palavra_chave'] = form.c_palavra_chave.data
        # video['conteudo']['data'] = form.cont_data.data
        # video['conteudo']['entidade'] = form.cont_entidade.data 
        # video['conteudo']['imagens'] = form.cont_imagens.data
        # video['conteudo']['comentarios'] = form.cont_comentarios.data
        return video